/**
 * Builds the demo page into src/server/web-assets.generated.ts (the page and one JS bundle that includes the engine),
 * so the server can serve it without reading files. Run after changing web/ or the engine:  npm run build:web
 * `npx tsx scripts/build-web.ts --check` fails if the committed file is out of date.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { build } from 'esbuild';

const root = new URL('../', import.meta.url).pathname;
const out = root + 'src/server/web-assets.generated.ts';

export async function render(): Promise<string> {
  const res = await build({
    entryPoints: [root + 'web/app.ts'],
    bundle: true,
    write: false,
    format: 'iife',
    target: 'es2022',
    minify: true,
    legalComments: 'none',
    charset: 'utf8',
  });
  const js = res.outputFiles[0]!.text;
  const html = readFileSync(root + 'web/index.html', 'utf8');
  return `// GENERATED by scripts/build-web.ts from web/index.html, web/app.ts and src/engine.ts. Do not edit by hand.\nexport const INDEX_HTML = ${JSON.stringify(html)};\nexport const APP_JS = ${JSON.stringify(js)};\n`;
}

if (process.argv[1]?.endsWith('build-web.ts')) {
  const next = await render();
  if (process.argv.includes('--check')) {
    const cur = readFileSync(out, 'utf8');
    if (cur !== next) {
      console.error('web-assets.generated.ts is out of date. Run: npm run build:web');
      process.exit(1);
    }
    console.log('web assets are up to date');
  } else {
    writeFileSync(out, next);
    console.log(`wrote ${out} (${(next.length / 1024).toFixed(1)} KB)`);
  }
}
